# Generated by Django 4.0.6 on 2023-04-02 16:58

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models

from apps.inmobiliaria.data import crear_datos_iniciales_inmobiliaria


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoInmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "icono",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                (
                    "foto",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("slug", models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name="Inmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barrio", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=100)),
                ("latitud", models.CharField(max_length=100)),
                ("longitud", models.CharField(max_length=100)),
                ("precioVenta", models.IntegerField()),
                ("precioArriendo", models.IntegerField()),
                ("numeroHabitaciones", models.IntegerField()),
                ("numeroBanios", models.IntegerField()),
                ("capacidadPersonas", models.IntegerField()),
                ("area", models.IntegerField()),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "foto",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("activo", models.BooleanField()),
                ("promocionado", models.BooleanField()),
                ("slug", models.SlugField()),
                ("fechaPublicacion", models.DateField(auto_now_add=True)),
                ("fechaActualizacion", models.DateField(auto_now=True)),
                ("usuario", models.CharField(blank=True, max_length=100, null=True)),
                ("telefono", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inmobiliaria.tipoinmueble",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FotoInmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                (
                    "inmueble",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inmobiliaria.inmueble",
                    ),
                ),
            ],
        ),
        migrations.RunPython(crear_datos_iniciales_inmobiliaria),
    ]
