# Generated by Django 4.0.6 on 2023-04-02 16:58

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models

from apps.directorio.data import crear_datos_iniciales_directorio


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaEstablecimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "icono",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                (
                    "foto",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Establecimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("horario", models.TextField()),
                ("direccion", models.CharField(max_length=100)),
                ("latitud", models.CharField(max_length=100)),
                ("longitud", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("telefono1", models.CharField(max_length=100)),
                ("telefono2", models.CharField(blank=True, max_length=100, null=True)),
                ("telefono3", models.CharField(blank=True, max_length=100, null=True)),
                ("sitioWeb", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "foto",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("activo", models.BooleanField()),
                ("promocionado", models.BooleanField()),
                ("slug", models.SlugField(unique=True)),
                ("fechaPublicacion", models.DateField(auto_now_add=True)),
                ("fechaActualizacion", models.DateField(auto_now=True)),
                ("usuario", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubcategoriaEstablecimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "icono",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                (
                    "foto",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directorio.categoriaestablecimiento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FotoEstablecimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                (
                    "establecimiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directorio.establecimiento",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="establecimiento",
            name="subcategoria",
            field=models.ManyToManyField(to="directorio.subcategoriaestablecimiento"),
        ),
        migrations.RunPython(crear_datos_iniciales_directorio),
    ]
