# Generated by Django 4.0.6 on 2023-04-02 16:58

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models

from apps.elecciones.data import crear_datos_iniciales_elecciones


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("activo", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Partido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "foto",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("sitioWeb", models.CharField(blank=True, max_length=100, null=True)),
                ("telefono", models.CharField(blank=True, max_length=100, null=True)),
                ("perfil", models.TextField(blank=True, null=True)),
                ("experiencia", models.TextField(blank=True, null=True)),
                ("propuestas", models.TextField(blank=True, null=True)),
                ("numeroTarjeton", models.IntegerField(blank=True, null=True)),
                ("activo", models.BooleanField()),
                ("promocionado", models.BooleanField()),
                (
                    "candidatura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="elecciones.candidatura",
                    ),
                ),
                (
                    "partido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="elecciones.partido",
                    ),
                ),
            ],
        ),
        migrations.RunPython(crear_datos_iniciales_elecciones),
    ]
